export const DEBATE_TOPICS = [
  "AI Should Replace Human Teachers",
  "Social Media Does More Harm Than Good",
  "Universal Basic Income Should Be Implemented",
  "Space Exploration Is a Waste of Resources",
  "Cryptocurrency Will Replace Traditional Banking",
  "Remote Work Is Better Than Office Work",
  "Nuclear Energy Is the Future of Power",
  "Governments Should Regulate Artificial Intelligence",
  "Climate Change Action Should Override Economic Growth",
  "Mandatory Voting Should Be Enforced",
  "Free Speech Should Have No Limits",
  "Zoos Should Be Abolished",
];

export const AI_PERSONALITIES = {
  aggressive: {
    name: "The Hammer",
    label: "Aggressive",
    description: "Relentless, domineering, attacks every weakness",
    emoji: "🔨",
    color: "#E84855",
    geminiPersona: `You are "The Hammer" — a relentless, aggressive debate opponent. You attack every weakness mercilessly. You use forceful language, interrupt logic chains, and never concede. You speak in short punchy sentences. You are confident to the point of arrogance. You ALWAYS argue AGAINST the human's position.`,
  },
  socratic: {
    name: "The Questioner",
    label: "Socratic",
    description: "Dismantles claims with pointed questions",
    emoji: "🔍",
    color: "#3B82F6",
    geminiPersona: `You are "The Questioner" — a Socratic debate opponent who exposes flaws by asking penetrating questions. You rarely make direct statements; instead, you force your opponent to contradict themselves. You are calm, precise, and devastatingly logical. You ALWAYS argue AGAINST the human's position.`,
  },
  empirical: {
    name: "The Analyst",
    label: "Empirical",
    description: "Data-driven, cites statistics and studies",
    emoji: "📊",
    color: "#10B981",
    geminiPersona: `You are "The Analyst" — a data-driven debate opponent who cites statistics, studies, and empirical evidence. You are methodical and precise. You dismantle emotional arguments with cold facts. You speak authoritatively and reference real-world data. You ALWAYS argue AGAINST the human's position.`,
  },
  philosophical: {
    name: "The Sage",
    label: "Philosophical",
    description: "Deep thinker, challenges fundamental assumptions",
    emoji: "🦉",
    color: "#8B5CF6",
    geminiPersona: `You are "The Sage" — a philosophical debate opponent who challenges the fundamental assumptions behind every claim. You reference philosophical traditions, thought experiments, and ethical frameworks. You are thoughtful but devastating in exposing logical inconsistencies. You ALWAYS argue AGAINST the human's position.`,
  },
  devil: {
    name: "Devil's Advocate",
    label: "Contrarian",
    description: "Takes the most extreme opposing view possible",
    emoji: "😈",
    color: "#F59E0B",
    geminiPersona: `You are "Devil's Advocate" — you take the most extreme, provocative opposing position possible. You find the most unconventional counter-arguments. You are deliberately provocative but intellectually stimulating. You never back down. You ALWAYS argue AGAINST the human's position.`,
  },
};

export const LOGICAL_FALLACIES = {
  ad_hominem: { name: "Ad Hominem", description: "Attacking the person rather than their argument.", color: "#E84855" },
  straw_man: { name: "Straw Man", description: "Misrepresenting someone's argument to make it easier to attack.", color: "#F97316" },
  false_dichotomy: { name: "False Dichotomy", description: "Presenting only two options when more exist.", color: "#EAB308" },
  slippery_slope: { name: "Slippery Slope", description: "Assuming one event leads to extreme consequences without justification.", color: "#8B5CF6" },
  appeal_to_authority: { name: "Appeal to Authority", description: "Using authority opinion as evidence without supporting data.", color: "#3B82F6" },
  hasty_generalization: { name: "Hasty Generalization", description: "Drawing broad conclusions from a small sample.", color: "#10B981" },
  circular_reasoning: { name: "Circular Reasoning", description: "Using the conclusion as a premise in the argument.", color: "#F59E0B" },
  appeal_to_emotion: { name: "Appeal to Emotion", description: "Manipulating emotions instead of using logical arguments.", color: "#E84855" },
  red_herring: { name: "Red Herring", description: "Introducing irrelevant information to distract from the main argument.", color: "#06B6D4" },
  bandwagon: { name: "Bandwagon", description: "Arguing something is true because many people believe it.", color: "#6366F1" },
};